#version: '3.3'

services:
    web:
        image: nginx:latest
        container_name: web_push_nginx
        restart: always
        ports:
            - "10010:80"
        volumes:
            - ./code:/code
            - ./sitelocal.conf:/etc/nginx/conf.d/default.conf
        networks:
            - web_push_net
    php:
        image: php:fpm
        container_name: web_push_php
        restart: always
        environment:
            ENVIRONMENT: dev
        command:
            - /bin/sh
            - -c
            - |
               apt update && apt -y install nano openssl
               rm -rf /etc/localtime && ln -s /usr/share/zoneinfo/Europe/Athens /etc/localtime
               cp /usr/local/etc/php/php.ini-production /usr/local/etc/php/php.ini
               echo 'date.timezone=Europe/Athens' >> /usr/local/etc/php/php.ini
               docker-php-ext-install mysqli pdo pdo_mysql
               php-fpm
        volumes:
            - ./code:/code
        networks:
            - web_push_net

networks:
    web_push_net:
        driver: bridge
